INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (1, 'A', N'Object-Oriented', 0);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (2, 'B', N'Object-Based', 0);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (3, 'C', N'Assembly-language', 0);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (5, 'D', N'High-level', 0);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (6, 'A', N'Alternative to if-else', 1);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (7, 'B', N'Switch statement', 1);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (8, 'C', N'If-then-else statement', 1);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (9, 'D', N'Immediate if', 1);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (10, 'A', N'===', 2);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (11, 'B', N'equals', 2);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (12, 'C', N'==', 2);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (13, 'D', N'Equals', 2);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (14, 'A', N'Global variable', 3);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (15, 'B', N'The local element', 3);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (16, 'C', N'The two of the above', 3);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (17, 'D', N'None of the above', 3);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (18, 'A', N'00', 5);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (19, 'B', N'0x', 5);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (20, 'C', N'0X', 5);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (22, 'D', N'Both 0x and 0X', 5);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (23, 'A', N'Prints an exception error', 8);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (24, 'B', N'Prints an overflow error', 8);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (25, 'C', N'Displays "Infinity"', 8);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (26, 'D', N'Prints the value as such', 8);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (27, 'A', N'Syntax error', 9);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (28, 'B', N'Missing of semicolons', 9);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (30, 'C', N'Division by zero', 9);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (31, 'D', N'Missing of Bracket', 9);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (32, 'A', N'toExponential()', 10);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (33, 'B', N'toFixed()', 10);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (34, 'C', N'toPrecision()', 10);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (35, 'D', N'LocaleString()', 10);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (36, 'A', N'toString()', 11);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (38, 'B', N'valueOf()', 11);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (39, 'C', N'toLocaleString()', 11);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (40, 'D', N'toPrecision()', 11);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (41, 'A', N'slice()', 12);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (42, 'B', N'split()', 12);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (43, 'C', N'substr()', 12);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (44, 'D', N'search()', 12);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (45, 'A', N'Both x and y are equal in value, type and reference address as well.', 13);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (47, 'B', N'Both are x and y are equal in value only.', 13);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (48, 'C', N'Both are equal in the value and data type.', 13);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (49, 'D', N'Both are not same at all.', 13);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (51, 'A', N'toString()', 14);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (52, 'B', N'String(human)', 14);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (53, 'C', N'String newvariable="human"', 14);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (54, 'D', N'Both human.toString() and String(human)', 14);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (55, 'A', N'Object Creation Expression', 15);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (56, 'B', N'Primary Expression', 15);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (57, 'C', N'Invocation Expression', 15);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (58, 'D', N'Constructor Calling Expression', 15);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (59, 'A', N'Exists', 16);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (60, 'B', N'exist', 16);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (61, 'C', N'within', 16);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (62, 'D', N'in', 16);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (63, 'A', N'?', 17);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (64, 'B', N':', 17);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (65, 'C', N'-', 17);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (66, 'D', N'+', 17);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (67, 'A', N'False', 18);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (68, 'B', N'True', 18);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (69, 'C', N'Nan', 18);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (70, 'D', N'Undefined', 18);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (71, 'A', N'undefined', 19);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (72, 'B', N'string', 19);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (73, 'C', N'boolean', 19);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (74, 'D', N'object', 19);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (75, 'A', N'if', 27);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (76, 'B', N'with', 27);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (77, 'C', N'debugger', 27);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (78, 'D', N'use strict', 27);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (79, 'A', N'The interpreter will jump to the one of the nearest enclosing exception handler', 28);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (80, 'B', N'The interpreter will throw another exception', 28);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (81, 'C', N'The interpreter will stop working', 28);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (82, 'D', N'The interpreter throws an error', 28);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (83, 'A', N'True', 29);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (84, 'B', N'False', 29);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (86, 'A', N'True', 31);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (87, 'B', N'False', 31);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (88, 'A', N'True', 32);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (89, 'B', N'False', 32);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (90, 'A', N'True', 33);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (91, 'B', N'False', 33);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (92, 'A', N'True', 34);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (93, 'B', N'False', 34);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (94, 'A', N'True', 35);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (95, 'B', N'False', 35);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (96, 'A', N'True', 36);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (97, 'B', N'False', 36);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (98, 'A', N'True', 37);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (99, 'B', N'False', 37);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (100, 'A', N'True', 38);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (101, 'B', N'False', 38);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (103, 'A', N'True', 40);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (104, 'B', N'False', 40);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (105, 'A', N'Data', 41);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (106, 'B', N'Information', 41);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (107, 'C', N'Tuple', 41);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (108, 'D', N'Attribute', 41);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (109, 'A', N'Flat file', 42);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (111, 'B', N'Database', 42);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (112, 'C', N'Data warehouse', 42);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (113, 'D', N'Enterprise database', 42);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (114, 'A', N'Data Base Model Structure', 43);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (115, 'B', N'Database Management Service', 43);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (117, 'C', N'Database Management System', 43);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (118, 'D', N'Data Base Management System', 43);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (119, 'A', N'DBMS is a collection of queries', 44);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (120, 'B', N'DBMS is a high-level language', 44);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (121, 'C', N'DBMS is a programming language', 44);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (122, 'D', N'DBMS stores, modifies and retrieves data', 44);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (123, 'A', N'Image oriented data', 45);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (124, 'B', N'Text, files containing data', 45);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (125, 'C', N'Data in the form of audio or video', 45);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (126, 'D', N'All of the above', 45);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (128, 'A', N'Image', 47);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (129, 'B', N'Text', 47);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (130, 'C', N'Table', 47);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (131, 'D', N'Graph', 47);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (132, 'A', N'Managing stored data', 48);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (133, 'B', N'Manipulating data', 48);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (134, 'C', N'Security for stored data', 48);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (135, 'D', N'Analyzing code', 48);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (136, 'A', N'Relation set', 51);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (137, 'B', N'Tuples
', 51);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (138, 'C', N'Entity set', 51);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (139, 'D', N'Entity Relation model', 51);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (140, 'A', N'Drop table', 52);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (141, 'B', N'Delete', 52);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (142, 'C', N'Purge', 52);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (143, 'D', N'Remove', 52);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (144, 'A', N'Delete from teaches;', 53);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (145, 'B', N'Delete from teaches where Id =’Null’;', 53);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (146, 'C', N'Remove table teaches;', 53);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (147, 'D', N'Drop table teaches;', 53);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (148, 'A', N'Left outer join', 56);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (149, 'B', N'Inner join', 56);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (150, 'C', N'Natural join', 56);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (151, 'D', N'Right outer join', 56);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (152, 'A', N'TCL (Transaction Control Language)', 58);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (153, 'B', N'DCL (Data Control Language)', 58);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (154, 'C', N'DDL (Data Definition Langauge)', 58);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (155, 'D', N'DML (Data Manipulation Langauge)', 58);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (156, 'A', N'Primary Key', 60);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (157, 'B', N'Foreign Key', 60);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (158, 'C', N'Super Key', 60);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (159, 'D', N'Candidate Key', 60);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (160, 'A', N'True', 61);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (161, 'B', N'False', 61);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (162, 'A', N'True', 62);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (163, 'B', N'False', 62);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (164, 'A', N'True', 63);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (165, 'B', N'False', 63);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (166, 'A', N'True', 64);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (167, 'B', N'False', 64);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (169, 'A', N'True', 65);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (170, 'B', N'False', 65);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (171, 'A', N'True', 66);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (172, 'B', N'False', 66);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (173, 'A', N'True', 67);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (174, 'B', N'False', 67);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (176, 'A', N'True', 69);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (177, 'B', N'False', 69);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (178, 'A', N'True', 70);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (179, 'B', N'False', 70);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (180, 'A', N'True', 72);
INSERT dbo.Choice(choice_id, choice_char, choice_description, que_id) VALUES (181, 'B', N'False', 72);
